name: udex
description: Acompanhamento de Processos Judiciais.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.13.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  flutter_svg: ^0.23.0+1
  provider: ^6.0.1
  http: ^0.13.3
  email_validator: '^2.0.1'
  dart_jsonwebtoken: ^2.3.0
  shared_preferences: ^2.0.6
  path_provider: ^2.0.2
  clipboard: ^0.1.3
  url_launcher: ^6.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^1.3.1
  flutter_launcher_icons: "^0.9.1"
  flutter_lints: ^1.0.3


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/keys/
